name: Run Pipeline on CSV changes

on:
  push:
    paths:
      - 'scatter/pipeline/inputs/*.csv'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          cd scatter
          pip install -r requirements.txt
      
      - name: Cache pipeline outputs
        uses: actions/cache@v3
        with:
          path: scatter/pipeline/outputs
          key: pipeline-outputs-${{ hashFiles('scatter/pipeline/inputs/*.csv') }}
          restore-keys: |
            pipeline-outputs-
      
      - name: Run pipeline
        run: |
          cd scatter/pipeline
          python main.py configs/example-polis.json --skip-interaction
        env:
          PYTHONPATH: ${{ github.workspace }}/scatter/pipeline
      
      - name: Setup Pages
        if: success()
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: scatter/pipeline/outputs/example-polis/report

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v2
